services:
  web:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - .:/app/
      - ./build/web/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # For troubleshooting with nginx, uncomment the below line
      # - ./data/logs:/var/log/nginx
    links:
      - php

  php:
    env_file:
      - build/env/local.env
    build:
      context: .
      dockerfile: build/php/Dockerfile
    volumes:
      - .:/app/
      - ./build/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini